#!/usr/bin/env bash
# Bash script that will display information about subdomains.

get_record_info() {
    local domain="$1"
    local subdomain="$2"

    local record_type=$(nslookup "$subdomain.$domain" | awk '/^Name:/{getline; print $2}')
    local destination=$(nslookup "$subdomain.$domain" | awk '/^Address:/{print $2}')

    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

main() {
    local domain="$1"
    local subdomain="$2"

    if [[ -z "$subdomain" ]]; then
        get_record_info "$domain" "www"
        get_record_info "$domain" "lb-01"
        get_record_info "$domain" "web-01"
        get_record_info "$domain" "web-02"
    else
        get_record_info "$domain" "$subdomain"
    fi
}
